version: '3'  
services:
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=adi
      - RABBITMQ_DEFAULT_PASS=adi
    networks:
      - network
  
  consumer:
    build: consumer
    environment:
      - AMQP_URL='amqp://adi:adi@rabbitmq?connection_attempts=5&retry_delay=5'
    networks:
      - network

  producer:
    build: producer
    environment:
      - AMQP_URL='amqp://adi:adi@rabbitmq?connection_attempts=5&retry_delay=5'
    networks:
      - network

networks:
  network: {}