version: '3'  
services:
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=adi
      - RABBITMQ_DEFAULT_PASS=adi
    networks:
      - network
  
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=adi
      - POSTGRES_PASSWORD=adi
    networks:
      - network

  backend:
    build: backend
    environment:
      - RABBITMQ_URL=amqp://adi:adi@rabbitmq/
      - POSTGRESQL_URL=postgresql+psycopg2://adi:adi@database:5432/transactions
    ports:
      - '8000:8000'
    depends_on:
      - rabbitmq
    networks:
      - network

  consumer:
    build: consumer
    environment:
      - MODE=docker
      - RABBITMQ_URL=amqp://adi:adi@rabbitmq/
      - POSTGRESQL_URL=postgresql+psycopg2://adi:adi@database:5432/transactions
    depends_on:
      - rabbitmq
    networks:
      - network

  producer:
    build: producer
    environment:
      - MODE=docker
      - RABBITMQ_URL=amqp://adi:adi@rabbitmq/
    depends_on:
      - rabbitmq
    networks:
      - network

networks:
  network: {}